#!/usr/bin/env bun
/**
 * Génère `packages/api-server/src/migrations-embedded.ts` à partir des
 * fichiers SQL dans `packages/db/src/migrations/`.
 *
 * Rationale : `bun build --compile` ne bundle PAS les fichiers `.sql` lus
 * via `readFileSync` à runtime. En prod (binaire MSI), `resolveMigrationsDir`
 * échoue avec "migrations introuvables" car le cwd est `C:\Program Files\FAKT`
 * et ni `import.meta.dir/../../db/src/migrations` ni `cwd/packages/db/src/...`
 * n'existent dans l'installation.
 *
 * Solution : au build-time, on lit les SQL, on les stringifie, et on génère
 * un module TS qui exporte `EMBEDDED_MIGRATIONS` comme array JS. Bundle Bun
 * embarque ce tableau nativement.
 *
 * Exécuté automatiquement par `build-sidecar.ts` avant `bun build`.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const thisFile = new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const packageRoot = resolve(dirname(thisFile), "..");
const repoRoot = resolve(packageRoot, "..", "..");
const migrationsDir = resolve(repoRoot, "packages", "db", "src", "migrations");
const outFile = resolve(packageRoot, "src", "migrations-embedded.ts");

function main(): void {
  const files = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  if (files.length === 0) {
    throw new Error(`Aucune migration .sql trouvée dans ${migrationsDir}`);
  }

  const migrations = files.map((name) => {
    const sql = readFileSync(join(migrationsDir, name), "utf8");
    return { name, sql };
  });

  const content = `/**
 * AUTO-GENERATED by \`scripts/generate-migrations.ts\` — DO NOT EDIT.
 * Source : packages/db/src/migrations/*.sql
 *
 * Bundlé dans le binaire Bun compilé pour que le sidecar ait accès aux
 * migrations même quand il tourne depuis \`C:\\Program Files\\FAKT\`
 * (aucun accès au dossier repo).
 */

export interface EmbeddedMigration {
  readonly name: string;
  readonly sql: string;
}

export const EMBEDDED_MIGRATIONS: readonly EmbeddedMigration[] = ${JSON.stringify(
    migrations,
    null,
    2
  )};
`;

  writeFileSync(outFile, content, "utf8");
  console.log(`[generate-migrations] ${files.length} migrations embarquées → ${outFile}`);
  for (const m of migrations) {
    const kb = (m.sql.length / 1024).toFixed(1);
    console.log(`  - ${m.name} (${kb} kB)`);
  }
}

main();
